additional_commands:
  FetchContent_Declare:
    kwargs:
      URL: '*'
      GIT_REPOSITORY: '*'
      GIT_TAG: '*'
      SOURCE_DIR: '*'
  HunterGate:
    kwargs:
      URL: '*'
      SHA1: '*'
    flags:
      - LOCAL

line_width: 100
tab_size: 2
max_subgroups_hwrap: 2
max_pargs_hwrap: 6
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
dangle_parens: false
dangle_align: prefix
min_prefix_chars: 4
max_prefix_chars: 10
max_lines_hwrap: 2
line_ending: unix
command_case: canonical
keyword_case: unchanged

always_wrap: []
enable_sort: true
autosort: true
hashruler_min_length: 10
per_command: {}
layout_passes: {}
bullet_char: '*'
enum_char: .
enable_markup: true
first_comment_is_literal: false
literal_comment_pattern: null
fence_pattern: ^\s*([`~]{3}[`~]*)(.*)$
ruler_pattern: ^\s*[^\w\s]{3}.*[^\w\s]{3}$
canonicalize_hashrulers: true
emit_byteorder_mark: false
input_encoding: utf-8
output_encoding: utf-8
